select * from employee;

update  employee set age=20 where first_name='MAYANK';

CREATE OR REPLACE PROCEDURE "INSERTUSER"
(FIRST_NAME IN VARCHAR2,
SALARY IN NUMBER,
AGE IN NUMBER)

IS

BEGIN
    INSERT INTO EMPLOYEE VALUES(FIRST_NAME,SALARY,AGE);
END;
/

SET SERVEROUTPUT ON;

BEGIN 
    INSERTUSER('KALAKHATTA',20000,33);
END;
/

SELECT * FROM EMPLOYEE;
